---
- hosts: tag_Project_new_t_e4
  become: true

  tasks:
    - name: Update system packages
      package:
        name: '*'
        state: latest
      become: yes
    - name: Install Apache (httpd)
      package:
        name: httpd
        state: present
      become: yes

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes
      become: yes

    - name: Install lrzsz
      package:
        name: lrzsz
        state: present
      become: yes

    - name: install wget
      package:
        name: wget
        state: present
      become: yes
